---
title: "File Structure and tutorial format"
author: "Josh Justison"
date: "`r Sys.Date()`"
output: html_document
---

### **Pracitcal Location and File Structure** 

All of the material needed for the practical sections of the course should be avaliable on the class [Github Repository](https://github.com/EEOB-Macroevolution/EEOB565X-Spring2020/tree/master/practicals). In this folder you will see the plethora of topics that we will be covering. Each folder should be a self-contained unit with all the nessecary files for a given tutorial. These folders all have the same structure, it can be helpful to familiarize yourself with this structure to ease finding tutorials and their associated materials. 

In each folder you should find the following files:

* **Macroevolutionary_Topic_Tutorial.html** This file will contain the tutorial for the given unit, this is what you'll be using the most.
* **readme.md** This is a text document that details the folders contents and any specific notes about the unit. It will also list the required R package needed for the tutorial, so this might be good to check before looking the tutorial.

You will also see a few different subfolders: 

* **scripts** This folder contains all the scripts used to generate data, run analyses, and create the tutorial. All of the code you see in the html tutorial can be found in the file that ends in `_code.r`. You will not find any code in the file ending in `.rmd`, that is the file used to create the html.
* **data** This folder will contain all the needed data files, usually trait data matrices and phylogenetic trees. We will cover in the first few tutorials on how to read these data into R.
* **figs** This folder contains any figures used in the tutorial. You likely won't need to access this folder unless you want to reference some of the figures. 

### **Tutorial Format**

Each tutorial has roughly the same structure and format. This guide will highlight a few of those things

#### **Sections**

##### Data Location

##### Learning Objectives

#### **Tutorial Components**

##### Code Blocks

##### Function Descriptions

##### Interactive Portions
